name: Android CI

on:
  push:
    branches: [ develop ]

jobs:

  unit-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout the code
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run unit test
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v1
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/
