name: Android CI

on:
  push:
    branches: [ "develop" ]

jobs:

  unit-test:
    name: Run Unit Tests
    runs-on: windows-latest
    
    steps:
      - name: Checkout the code
      - uses: actions/checkout@v2

      - name: Run unit test
        run: ./gradlew test

      - name: Upload unit test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/
